### ISSUE TITLE
Import Latitude, Longitude and LocationDesc from CA Service Desk/CMDB?

### ISSUE THREAD

**Issue by nelsonpita** [CA-PM/Google-WeatherMap#1]
Hi,

I have in CA Service Desk all the info regarding routers and switches (like latitude, longitude and location).
How can I import all this info for not have to write again all the info for each equipment?
Any way to synchronize this info?

Thanks,
NP

**Comment by bclairmont** [comment]
You can use the restful web services on the data aggregator to update the attributes on per device basis. The web service documentation can be found on your data aggregator using the following link:
http://<da>:8581/rest/devices/documentation

You could then build a script to pull in the data from your service desk to populate in CAPM.
