### ISSUE TITLE
CA-PM Center point adjustment

### ISSUE THREAD

**Issue by Praveensamfdo** [CA-PM/Google-WeatherMap#4]
How to adjust the center point of the CA-PM Google-WeatherMap . What parameters needs to be changed . Please assist.

**Comment by kamalmanchanda88** [comment]
You can customize index.html file located under /opt/CA/PerformanceCenter/PC/webapps/pc/apps/user/Google-WeatherMap-master

Change the lat and lng values, you can additionally change zoom value to focus
spinner.stop();
        var myLatLng = {lat: 7.290572, lng: 80.633728};
         var mapOptions = {
              styles: lightGreyTheme,
              zoom: 7.5,
              center: myLatLng,
              minZoom: 4

**Comment by Praveensamfdo** [comment]
Thanks Kamal...
